### PR TITLE
Signing LightInject to give it a strong name

### PR DESCRIPTION
**Pull request by arlm**

### CODE REVIEW

**Comment by seesharper** [comment]
This issue has already been discussed here (#207) 
As mentioned in this issue, you can still sign assemblies using a third party tool.
http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm

Any particular reason you want to sign your assemblies? 

https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

**Comment by arlm** [comment]
Well, I understand the implications on assembly redirection. I must disagree with you when you say it has already been discussed on #207, because there were no discussion, just a statement, sorry.

As for the reason, it is that we must run the code on FullTrust environment so our DLLs must be strong-named and LightInject does not get loaded on all my tests. Maybe there is a way to reference non-strong-named DLLs on this case, but I am not aware of that.

About the redirection problem, I sincerely don't think that is a problem. Someone that wants to update a library should recompile it when there are major version changes and minor version changes I guess that are  handled by the run-time without problems and without need to to redirects. The semantic versioning ensures that all breaking changes goes to major version number changes and then they guy has to recompile anyway,

**Comment by arlm** [comment]
But I respect that it is the decision of the goal for this project.

**Comment by arlm** [comment]
This could be closed as rejected then.

**Pull request closed without merging**
