### PR TITLE
Make all IServiceRegistry calls return itself for fluent chaining

### PR DESCRIPTION
**Pull request by geirsagberg**
Implements #295.

I suppose this change might need a major version change if strictly following SemVer?

### CODE REVIEW

**Comment by seesharper** [comment]
Do we really need to update the Major version? It is still compatible with the old version

**Comment by geirsagberg** [comment]
I was thinking if someone has implemented `IServiceRegistry`, their implementation would break because the interface now has a return value. I'm not a SemVer purist though, just thought I should mention it :)

**Comment by seesharper** [comment]
I went with bumping the minor version. 4.1.0 just published to the official NuGet feed

**Comment by seesharper** [comment]
This change sort of rippled down to all libraries that depend upon LightInject. 

http://stackoverflow.com/questions/9178533/why-adding-a-return-type-to-a-void-returning-method-causes-a-missingmethodexcept

I might need to bump the major as well. Pushing trough on this one and it will not be reverted.

**Comment by geirsagberg** [comment]
Yikes, wasn't aware changing return types would break all dependents. Sorry for the trouble, need any help updating the extension repos?

**Comment by seesharper** [comment]
I might, I going to create a 5.0.0 version of LightInject first and then we have to go through all extension repos and update the LightInject Nuget package reference.
In addition we need to updated the NuSpec files in these repose so that they require the latest LightInject version. 

I’ll let you know when 5.0.0 is out. 

I am also moving SignalR out into its own repo making that extension easier to maintain as well

**Comment by seesharper** [comment]
Question is. Do we need to bump the major on the extensions too?

**Comment by geirsagberg** [comment]
Good question; my first thought would be no, since the extensions themselves do not have any interface changes. One would have to test it to be sure though.

**Comment by geirsagberg** [comment]
I sent a bunch of PRs for the extension repos; while they reference 4.1.0 and not 5.0.0, at least it will stop breakage when updating from NuGet.

**Pull request merged**
