### PR TITLE
Make EnablePerWebRequestScope extend IServiceContainer

### PR DESCRIPTION
**Pull request by geirsagberg**
Instead of ServiceContainer.

### CODE REVIEW

**Comment by torgeir** [comment]
:+1:

**Comment by geirsagberg** [comment]
@seesharper Anything blocking this merge?

**Comment by seesharper** [comment]
Currently rewriting the build system for LightInject. I will try to get a new Nuget package out as soon as possible.

**Comment by geirsagberg** [comment]
Great, thanks :)

**Pull request merged**
